name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Update Dates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: XHenryJaquesX
          github_token: ${{ secrets.GITHUB_TOKEN }}
